---
name: Release - Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

jobs:
  check-inputs:
    name: Check inputs validity
    runs-on: ubuntu-latest
    steps:
      - id: check
        run: |
          echo "${{ inputs.version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
  bump:
    name: Bump gravity version
    needs:
      - check-inputs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - uses: ./.github/actions/setup
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          sed -i 's/VERSION = ".*"/VERSION = "${{ inputs.version }}"/g' Makefile
          git add Makefile
          make release
      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v${{ inputs.version }}"
          name: Release ${{ inputs.version }}
          draft: true
          generate_release_notes: true
          body: |
            Upgrade to this version of gravity by using this container image:

            ```
            ghcr.io/beryju/gravity:v${{ inputs.version }}
            ```

            Upgrade to the current JS API Client using

            ```
            npm i gravity-api@${{ inputs.version }}
            ```

            Upgrade to the current Golang API Client using

            ```
            go get beryju.io/gravity@v${{ inputs.version }}
            ```

            Upgrade external-dns to use this container image:

            ```
            ghcr.io/beryju/gravity-external-dns:v${{ inputs.version }}
            ```
